### ISSUE TITLE
Can't use the utility

### ISSUE THREAD

**Issue by locksoft** [yahesh/extract-webarchive#1]
Hi, I'm trying to extract a .webarchive but I only get a "No such file or directory" error.

What am I doing wrong?

![Screenshot 16](https://github.com/user-attachments/assets/f6c78b40-4249-47af-930e-db287dcf0661)

**Comment by yahesh** [comment]
@locksoft It's a PHP script so you need to have PHP installed on your machine.

**Comment by yahesh** [comment]
Tested it on macOS 15.1.1. Still works as expected.

**Comment by locksoft** [comment]
I can't understand what's the problem for me, then. If you look at the screenshot, what am I doing wrong (I'm not an Unix expret, btw)?
I just wanted to unpack the "mi.webarchive" inside the "MI" directory.

**Comment by locksoft** [comment]
Thank you. :)
